### ISSUE TITLE
Release `5.48.0`

### ISSUE THREAD

**Issue by zees-dev** [futureversecom/trn-seed#769]
# Release

**Release Name:** `5.48.0`

**Spec Version:** `48`

**Client Version:** `5.0.0`

## Key Changes:

This release introduces the following changes:

- Introduced NFT marketplace precompile; can be used to create NFTs and sell them on the marketplace via solidity interface at `0x00000000000000000000000000000000000006CD`
  - https://github.com/futureversecom/trn-seed/pull/696
- Unified RPC call to get balance for root and other assets
  - https://github.com/futureversecom/trn-seed/pull/728
- Transactions include a sourceTag for XRPL withdraw (bridging TRN->XRPL)
  - https://github.com/futureversecom/trn-seed/pull/742
- ERC721 precompile [Burnable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/ERC721Burnable.sol) support
  - https://github.com/futureversecom/trn-seed/pull/746
- Update/fix state fork script
  - https://github.com/futureversecom/trn-seed/pull/752
- Update self contained call interfaces (future PR pre-req)
  - https://github.com/futureversecom/trn-seed/pull/753
- Fix ERC20 pre-crompile to validate maintenance mode restrictions
  - https://github.com/futureversecom/trn-seed/pull/759
- Delay large XRPL bridging transactions
  - https://github.com/futureversecom/trn-seed/pull/761
- Update bootnode list for Porcini and Root
  - https://github.com/futureversecom/trn-seed/pull/764
- Optimized gas required for contract deployment by removing fee
  - https://github.com/futureversecom/trn-seed/pull/765
- ERC20 precompile asset existence verification
  - https://github.com/futureversecom/trn-seed/pull/767

---

## Client Changes:
- [x] Yes
- [ ] No

#### Added:

**pallet-assets-ext-rpc-runtime-api**:

- free_balance (`freeBalance`)

---

## Runtime Changes:
- [x] Yes
- [ ] No

#### Added:

**pallet-evm-precompiles-marketplace**:

- registerMarketplace
- sellNftWithMarketplaceId
- sellNftWithoutMarketplace
- updateFixedPrice
- buy
- auctionNftWithMarketplaceId
- auctionNftWithoutMarketplace
- bid
- cancelSale
- makeSimpleOfferWithMarketplaceId
- makeSimpleOfferWithoutMarketplace
- cancelOffer
- acceptOffer

**pallet-evm-precompiles-erc20**:

- burn

#### Changed:

**pallet-evm-precompiles-erc20**:
- transfer

#### Added:

**pallet-xrpl-bridge**:

- PaymentDelay
- DelayedPayments
- DelayedPaymentSchedule
- NextDelayProcessBlock
- NextDelayedPaymentId

#### Added:

**pallet-xrpl-bridge**:

- set_payment_delay

#### Changed:

**pallet-xrpl-bridge**:

- withdraw_xrp_with_destination_tag
- set_xrp_source_tag

#### Added:

**pallet-xrpl-bridge**:

- PaymentDelaySet
- PaymentDelayRemoved
- WithdrawDelayed

#### Added:

**pallet-xrpl-bridge**:

- NoAvailablePaymentIds
- DelayScheduleAtCapacity

**Comment by surangap** [comment]
`pallet-xrpl-bridge` extrinsic section should be updated as  add  `withdraw_xrp_with_destination_tag`, `set_xrp_source_tag` and no changes to `withdraw_xrp`

**Comment by zees-dev** [comment]
> * `pallet-xrpl-bridge` extrinsic section should be updated as  add  `withdraw_xrp_with_destination_tag`, `set_xrp_source_tag` and no changes to `withdraw_xrp`
> * [Add limit to number of pruned txs per block in on_idle #751](https://github.com/futureversecom/trn-seed/pull/751) should be removed. deployed with a previous release

`withdraw_xrp` has internally changed however

**Comment by surangap** [comment]
> > * `pallet-xrpl-bridge` extrinsic section should be updated as  add  `withdraw_xrp_with_destination_tag`, `set_xrp_source_tag` and no changes to `withdraw_xrp`
> > * [Add limit to number of pruned txs per block in on_idle #751](https://github.com/futureversecom/trn-seed/pull/751) should be removed. deployed with a previous release
> 
> `withdraw_xrp` has internally changed however
we use the same member functions to support both. but no changes to the signature or the functionality of `withdraw_xrp`.

**Comment by KarishmaBothara** [comment]
- Transactions include a sourceTag for XRPL withdraw (bridging TRN->XRPL)
   https://github.com/futureversecom/trn-seed/pull/742

This also adds a new withdraw extrinsic that supports DestinationTag (withdraw_xrp_with_destination_tag)

**Comment by ken-centrality** [comment]
are we good to close this @zees-dev ?

**Comment by zees-dev** [comment]
> are we good to close this @zees-dev ?

yee
